### ISSUE TITLE
[求助] 能否在人物卡里读取人物捏脸数据？

### ISSUE THREAD

**Issue by ChasonJiang** [GenesisAN/illusionsCard#1]
你好，我有一个项目需要获取人物的捏脸数据。请问能否在人物卡里面直接获取呢？如果能的话，如何找到并读取呢？如果您知道的话，非常期待您的解答。

**Comment by GenesisAN** [comment]
可以，具体可参考
https://github.com/GenesisAN/illusionsCard/blob/8ec0e3db790cc90cfc1cfa52280c4bcf3f06e8a1/KKS/KKSCard.go#L80-L94
这里演示了Parameter数据的读取，捏脸可能保存在这个map的key”Custom”的value里，或者是其他key里。
I社采用MsgPack格式序列化卡片数据

**Comment by ChasonJiang** [comment]
> 可以，具体可参考
> 
> https://github.com/GenesisAN/illusionsCard/blob/8ec0e3db790cc90cfc1cfa52280c4bcf3f06e8a1/KKS/KKSCard.go#L80-L94
> 
> 
> 这里演示了Parameter数据的读取，捏脸可能保存在这个map的key”Custom”的value里，或者是其他key里。
> I社采用MsgPack格式序列化卡片数据

好的，了解了，非常感谢
